const calcium = {
  nom: "Calcium",

  origine: `Le calcium est un minéral alcalino-terreux abondamment présent dans la croûte terrestre, reconnu comme nutriment essentiel pour l’organisme humain. Historiquement, son rôle dans la minéralisation osseuse a été identifié au XIXe siècle, bien avant que ses implications physiologiques plus subtiles ne soient élucidées. Il est naturellement contenu dans de nombreux aliments comme les produits laitiers, les légumes verts (brocoli, chou frisé), certaines eaux minérales, ou encore les poissons consommés avec leurs arêtes (sardines, maquereaux). Dans la médecine traditionnelle, les coquilles d’huîtres ou de corail étaient parfois broyées pour en faire des remèdes contre les douleurs osseuses ou dentaires. Le calcium constitue environ 1 à 2 % du poids corporel total, localisé à plus de 99 % dans les os et les dents, le reste jouant des rôles critiques dans les cellules musculaires, nerveuses et vasculaires.`,

  formes_disponibles: `Le calcium est disponible sous différentes formes : comprimés, gélules, poudres, solutions buvables, et gommes à mâcher. Les principales formes chimiques incluent le carbonate de calcium, le citrate de calcium, le lactate de calcium, et le gluconate de calcium. Le carbonate est le plus courant pour sa teneur élevée en calcium élémentaire (40 %), tandis que le citrate est préféré pour sa meilleure tolérance digestive, notamment chez les personnes souffrant d’hypochlorhydrie. Certains compléments associent le calcium à la vitamine D, au magnésium ou à la vitamine K2 pour optimiser son utilisation osseuse. Des formes enrichies existent aussi dans des laits végétaux, des jus de fruits ou des barres nutritionnelles.`,

  formes_recommandees_biodispo: `La biodisponibilité du calcium dépend fortement de sa forme chimique, du pH gastrique, de la présence d’autres nutriments et du moment de la prise. Le carbonate de calcium doit être pris au cours d’un repas pour maximiser son absorption, tandis que le citrate peut être pris à jeun, car il ne nécessite pas un environnement acide. Le citrate de calcium montre une meilleure biodisponibilité dans les populations âgées ou les personnes sous inhibiteurs de pompe à protons. L’absorption intestinale du calcium est d’environ 20 à 30 %, mais elle diminue lorsque les apports sont très élevés ou en cas de carence en vitamine D. Des études ont montré que la prise fractionnée du calcium (deux à trois fois par jour) améliore son assimilation par rapport à une dose unique élevée.`,

  pharmacocinetique: `Le calcium est absorbé principalement dans le duodénum et le jéjunum proximal par deux mécanismes : actif transcellulaire (régulé par la vitamine D) et passif par diffusion. Son Tmax varie entre 2 et 4 heures selon la forme et la co-ingestion alimentaire. Une fois dans la circulation, il est transporté soit librement (ionisé, forme biologiquement active), soit lié à l’albumine. La demi-vie du calcium plasmatique libre est courte (quelques heures), car il est étroitement régulé par les hormones parathyroïdiennes, la calcitonine et la vitamine D. Les excès sont excrétés par les reins, les selles ou la sueur. Il n’existe pas de mécanisme d’accumulation chronique en dehors de cas pathologiques (hypercalcémie).`,

  mecanisme_action: `Le calcium intervient dans une multitude de processus physiologiques. Il est indispensable à la minéralisation osseuse via la formation d’hydroxyapatite avec le phosphate. Au niveau cellulaire, il joue un rôle dans la contraction musculaire (liaison à la troponine dans le muscle squelettique), dans la transmission nerveuse (entrée de calcium présynaptique déclenchant la libération des neurotransmetteurs), et dans la signalisation intracellulaire (activation de protéines kinases, phosphatases, et voies calmodulino-dépendantes). Il participe également à la coagulation sanguine en activant certains facteurs (II, VII, IX, X) et au maintien de la perméabilité membranaire. Son homéostasie est régulée par l’interaction complexe entre la parathormone, la vitamine D et la calcitonine.`,

  synergies: `Le calcium agit en synergie avec la vitamine D, qui stimule l’expression des transporteurs calciques intestinaux et augmente l’absorption. La vitamine K2 (ménaquinone) favorise sa fixation dans le tissu osseux en activant l’ostéocalcine, tout en limitant les dépôts artériels. Le magnésium est un cofacteur de la parathormone et intervient dans la sensibilité des récepteurs calciques. Une alimentation trop riche en sodium ou en protéines animales augmente l’excrétion urinaire du calcium. L’équilibre calcium/phosphore est aussi déterminant dans la régulation de la minéralisation osseuse.`,

  bienfaits: `La supplémentation en calcium, associée à la vitamine D, réduit le risque de fractures ostéoporotiques chez les sujets âgés (source : Tang et al., *The Lancet*, 2007). Elle permet de ralentir la perte osseuse post-ménopausique (source : Reid et al., *American Journal of Medicine*, 1993). Chez les adolescents, elle optimise le pic de masse osseuse (source : Bonjour et al., *Journal of Clinical Endocrinology & Metabolism*, 1991). Des effets plus modestes sont rapportés sur la pression artérielle (source : Griffith et al., *Journal of Human Hypertension*, 1999).`,

  inconvenients: `À fortes doses (>1500 mg/j), le calcium peut entraîner des troubles gastro-intestinaux (constipation, ballonnements), des calculs rénaux chez les sujets prédisposés, et interférer avec l’absorption de certains médicaments (lévothyroxine, bisphosphonates, antibiotiques tétracyclines). Un apport excessif sans cofacteurs (vitamine D, K2) peut favoriser la calcification vasculaire. Des controverses subsistent quant à son effet cardiovasculaire chez les personnes âgées supplémentées sans déficit documenté (source : Bolland et al., *BMJ*, 2010).`,

  conseils_utilisation: `Les apports recommandés varient selon l’âge et le sexe : 1000 mg/j pour les adultes, 1200 à 1500 mg/j chez les femmes post-ménopausées ou les personnes âgées. Il est conseillé de privilégier les formes bien tolérées comme le citrate chez les personnes âgées ou souffrant de troubles digestifs. La supplémentation doit être fractionnée, idéalement en deux prises avec les repas. En cas de déficit en vitamine D, il est préférable de corriger celui-ci avant d’augmenter les apports calciques. Chez les sportifs ou en période de croissance, les besoins peuvent être majorés.`,

  certifications: `Il est recommandé de choisir des compléments certifiés GMP, ou testés par des tiers indépendants pour garantir leur pureté et leur biodisponibilité. Les produits indiquant clairement la teneur en calcium élémentaire sont préférables. Il faut éviter les formulations contenant du plomb, des métaux lourds ou des excipients controversés. La mention du type de sel (carbonate, citrate, etc.) est essentielle pour évaluer la tolérance et l’absorption.`,

  conclusion: `Le calcium est un minéral vital pour la santé osseuse, musculaire et neuromusculaire. Sa supplémentation peut être utile dans les contextes de croissance, de vieillissement ou de déficience avérée. Toutefois, elle doit toujours être pensée dans une logique de complémentation raisonnée, accompagnée des cofacteurs nécessaires à sa bonne utilisation, afin d’éviter les effets secondaires ou les inefficacités liées à un excès isolé.`
};

export default calcium;
