const cannelle = {
  nom: "Cannelle",

  origine: `La cannelle est une épice obtenue à partir de l'écorce intérieure des arbres du genre Cinnamomum, principalement Cinnamomum verum (cannelle de Ceylan) et Cinnamomum cassia (cannelle de Chine). Son usage remonte à plusieurs millénaires, notamment en Égypte ancienne où elle servait à l'embaumement, mais aussi en médecine traditionnelle chinoise, ayurvédique et perse pour ses vertus digestives, stimulantes et antiseptiques. Importée en Europe au Moyen Âge par les routes arabes, elle a longtemps été un produit de luxe réservé à la pharmacopée des élites. Aujourd’hui encore, elle est largement utilisée tant comme condiment que comme complément alimentaire pour ses propriétés antioxydantes et métaboliques.`,

  formes_disponibles: `La cannelle est disponible sous forme de bâtons, de poudre, d’huiles essentielles, d’extraits secs titrés, de gélules, de comprimés et de teintures alcooliques. Les compléments alimentaires contiennent en général de l’extrait sec de Cinnamomum cassia ou de Ceylan standardisé en cinnamaldéhyde ou en polyphénols. L'huile essentielle, très concentrée en cinnamaldéhyde, est parfois utilisée pour ses effets antimicrobiens, mais nécessite des précautions en raison de sa puissance.`,

  formes_recommandees_biodispo: `Les extraits secs titrés standardisés sont généralement recommandés pour un usage complémentaire, car ils garantissent une teneur contrôlée en principes actifs (polyphénols, cinnamaldéhyde). La poudre brute, bien que plus courante, présente une biodisponibilité variable et dépendante du mode d’administration (ex : prise avec des lipides). L'huile essentielle n’est pas recommandée en usage interne sans encadrement professionnel, car elle peut être toxique à forte dose. La forme aqueuse (tisane) est moins concentrée, mais utile pour un usage quotidien léger.`,

  pharmacocinetique: `Le cinnamaldéhyde, principal actif de la cannelle, est absorbé dans l’intestin grêle, puis métabolisé dans le foie en acide cinnamique. Ce dernier est ensuite converti en benzoate de sodium ou d’autres composés hydrosolubles excrétés par voie urinaire. Le Tmax est estimé entre 1 et 3 heures selon la forme, avec une demi-vie courte (inférieure à 4 heures). Une prise répétée est donc nécessaire pour maintenir un effet stable. Les effets antioxydants sont en partie liés à la présence de polyphénols dont la cinétique est plus lente, avec une persistance plasmatique prolongée.`,

  mecanisme_action: `La cannelle agit via plusieurs mécanismes biologiques : inhibition des enzymes digestives (α-amylase, α-glucosidase), stimulation de l’activité de l’insuline, et amélioration de la captation du glucose par les tissus périphériques. Elle possède également des effets anti-inflammatoires via la modulation du facteur NF-κB, ainsi que des effets antimicrobiens contre diverses souches bactériennes et fongiques. Les polyphénols qu’elle contient renforcent ses effets antioxydants, notamment en réduisant les radicaux libres au niveau hépatique et vasculaire.`,

  synergies: `La cannelle peut être associée au chrome pour renforcer ses effets sur la régulation glycémique. Combinée au gingembre ou au curcuma, elle soutient l’activité anti-inflammatoire via des voies communes de signalisation cellulaire. La prise conjointe avec un repas riche en glucides améliore le contrôle postprandial de la glycémie.`,

  bienfaits: `Des études ont montré une baisse significative de la glycémie à jeun (-10 à -29 %) après supplémentation en cannelle pendant 4 à 12 semaines chez des patients diabétiques de type 2 (source : Khan et al., *Diabetes Care*, 2003). Une méta-analyse a confirmé l’amélioration du profil lipidique (baisse du LDL, hausse du HDL) (source : Allen et al., *Annals of Family Medicine*, 2013). Elle améliore également la sensibilité à l’insuline et pourrait avoir des effets positifs sur la tension artérielle et les marqueurs inflammatoires.`,

  inconvenients: `La cannelle de Cassia contient des quantités significatives de coumarine, un composé hépatotoxique à haute dose. Des cas de toxicité hépatique ont été rapportés après consommation prolongée de doses élevées (source : Abraham et al., *Food and Chemical Toxicology*, 2010). Elle peut également provoquer des allergies de contact ou d’irritation digestive. L’usage de l’huile essentielle par voie orale est déconseillé sans supervision médicale. Des interactions sont possibles avec les anticoagulants (coumarine) ou les antidiabétiques.`,

  conseils_utilisation: `La posologie recommandée est généralement de 1 à 3 g de poudre de cannelle par jour, ou 250 à 500 mg d’extrait sec titré (cinnamaldéhyde ou polyphénols). Elle doit être prise au cours des repas pour limiter les pics glycémiques. Chez les diabétiques, la cannelle ne doit jamais remplacer un traitement médical mais peut s’intégrer en complément. Une cure de 8 à 12 semaines est souvent proposée, suivie d’une période de pause. La cannelle de Ceylan est à privilégier pour un usage prolongé, car moins riche en coumarine.`,

  certifications: `Il est conseillé de choisir des compléments certifiés GMP, indiquant la variété (Ceylan ou Cassia), la teneur en cinnamaldéhyde ou en polyphénols, et exempt de métaux lourds. Les produits issus d’agriculture biologique limitent les risques de résidus de pesticides. L’absence d’additifs synthétiques et la standardisation de la composition sont des gages de qualité.`,

  conclusion: `La cannelle est un complément alimentaire aux effets métaboliques documentés, particulièrement utile dans le cadre du syndrome métabolique et du diabète de type 2. Son efficacité dépend de la variété choisie, de la forme galénique et du contexte d’utilisation. Elle doit être consommée avec précaution à fortes doses, en raison de la présence potentielle de coumarine dans la cannelle de Cassia. Intégrée intelligemment à une routine nutritionnelle, elle peut représenter un outil intéressant pour la gestion glycémique et l’inflammation.`
};

export default cannelle;